export const API_CONFIG = {
  TWINWORD_API_KEY: process.env.REACT_APP_TWINWORD_API_KEY,
  TWINWORD_API_HOST: process.env.REACT_APP_TWINWORD_API_HOST,
  TWINWORD_API_URL: process.env.REACT_APP_TWINWORD_API_URL,
};
